baseURL = "https://pride.codes/"
languageCode = "en-us"
title = "pride.codes"

theme = "pride-codes"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Proudly celebrating engineering diversity."
  copyright = ""
  sidebarAbout = [
    "pride.codes provides a collection of simple widgets for businesses to add to their sites. We want businesses to show their support for their LGBTQI+ colleagues who are affected by this vote, regardless of their corporate political stance.",
    "The site offers a range of widgets to fly the flag. A collection of political flags is also available for those who are taking stronger #VoteYes position."
  ]
  email = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  # [[params.navlinks]]
  # name = "Get in touch"
  # url = "contact/"

  [params.social]
  email         = "email@example.com"
  twitter       = "https://twitter.com/pridecodes"
  github        = "https://github.com/devjack/pride.codes"

[[params.meta]]
    property="og:type"
    content="article"
[[params.meta]]
    property="og:title"
    content="pride.codes"
[[params.meta]]
    property="og:site_name"
    content="pride.codes"
[[params.meta]]
    property="og:url"
    content="https://pride.codes"
[[params.meta]]
    property="og:image"
    content="https://cdn.pride.codes/img/logo_png_small.png"
[[params.meta]]
    property="article:published_time"
    content="2017-09-12"
[[params.meta]]
    property="article:author"
    content="https://www.twitter.com/developerjack"
[[params.meta]]
    property="article:author"
    content="https://www.twitter.com/_patmurray"
