baseURL = "https://pride.codes/"
languageCode = "en-us"
title = "pride.codes"

theme = "pride-codes"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-106326008-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Proudly celebrating engineering diversity."
  copyright = ""
  sidebarAbout = [
    "pride.codes provides a collection of simple widgets for businesses to add to their sites. We want businesses to show their support for their LGBTQI+ colleagues who are affected by this vote, regardless of their corporate political stance.",
    "The site offers a range of widgets to fly the flag. A collection of political flags is also available for those who are taking stronger #VoteYes position."
  ]
  email = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  # [[params.navlinks]]
  # name = "Get in touch"
  # url = "contact/"

  [params.social]
  twitter       = "https://twitter.com/pridecodes"
  github        = "https://github.com/devjack/pride.codes"
